name: Fetch HackerNews Stories

on:
  schedule:
    - cron: "0 0,4,9,13 * * *" # 北京时间 8:00, 12:00, 17:00, 21:00
  workflow_dispatch: # 允许手动触发

jobs:
  fetch-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create public directory
        run: mkdir -p public

      - name: Fetch stories and generate HTML
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_API_BASE: ${{ vars.OPENAI_API_BASE }}
          OPENAI_MODEL: ${{ vars.OPENAI_MODEL }}
          PYTHONUNBUFFERED: 1
        run: |
          echo "=== 环境检查 ==="
          echo "Python 版本:"
          python --version

          # 检查环境变量
          if [ -n "$OPENAI_API_KEY" ]; then
            echo "OPENAI_API_KEY: 已设置"
          else
            echo "OPENAI_API_KEY: 未设置"
            exit 1
          fi

          # 显示变量值（因为这些不是敏感信息）
          echo "OPENAI_API_BASE: ${OPENAI_API_BASE:-使用默认值}"
          echo "OPENAI_MODEL: ${OPENAI_MODEL:-使用默认值}"

          echo "================"
          python scripts/fetch_hn.py

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
          keep_files: false
